/* The following code was generated by JFlex 1.3.5 on 2/27/04 2:46 PM */

/* JavaLexer.java is a generated file.  You probably want to
 * edit JavaLexer.lex to make changes.  Use JFlex to generate it.
 * To generate JavaLexer.java
 * Install <a href="http://jflex.de/">JFlex</a> v1.3.2 or later.
 * Once JFlex is in your classpath run<br>
 * <code>java JFlex.Main JavaLexer.lex</code><br>
 * You will then have a file called JavaLexer.java
 */

/*
 * This file is part of a <a href="http://ostermiller.org/syntax/">syntax
 * highlighting</a> package.
 * Copyright (C) 1999-2002 Stephen Ostermiller
 * http://ostermiller.org/contact.pl?regarding=Syntax+Highlighting
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * See COPYING.TXT for details.
 */

package eecs.syntax.Lexer;

import java.io.*;

/** 
 * JavaLexer is a java lexer.  Created with JFlex.  An example of how it is used:
 *  <CODE>
 *  <PRE>
 *  JavaLexer shredder = new JavaLexer(System.in);
 *  JavaToken t;
 *  while ((t = shredder.getNextToken()) != null){
 *      System.out.println(t);
 *  }
 *  </PRE>
 *  </CODE>
 * The tokens returned should comply with the 
 * <A Href=http://java.sun.com/docs/books/jls/html/>Java 
 * Language Specification</A>.
 * @see JavaToken
 */ 


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 2/27/04 2:46 PM from the specification file
 * <tt>file:/C:/Gossett/jflex/bin/JavaLexer.lex</tt>
 */
public class JavaLexer implements Lexer {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  7,  9,  0,  7,  9,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     7, 44, 18,  0,  6, 10, 48, 17, 33, 34, 20, 21, 40, 22, 32, 19, 
     4,  5,  5,  5,  3,  3,  3,  3,  2,  2, 47, 39, 43, 41, 42, 46, 
     0,  1,  1,  1, 31, 28, 29,  6,  6,  6,  6,  6, 24, 65,  6,  6, 
     6,  6,  6, 64,  6,  6,  6,  6, 26,  6,  6, 37,  8, 38, 50,  6, 
     0, 51, 14, 53, 30, 27, 15, 59, 57, 58,  6, 55, 23, 60, 13, 54, 
    61,  6, 12, 52, 16, 11, 62, 63, 25, 56, 66, 35, 49, 36, 45,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    67,   134,   201,   268,   335,   402,   469,   536,   603, 
      670,   737,   804,   871,   938,  1005,  1072,  1139,  1206,  1273, 
     1340,  1407,  1474,  1541,  1541,  1541,  1541,  1541,  1541,  1541, 
     1541,  1608,  1675,  1742,  1809,  1541,  1541,  1541,  1876,  1943, 
     2010,  2077,  2144,  2211,  2278,  2345,  2412,  2479,  2546,  2613, 
     2680,  2747,  2747,  2747,  2814,  2747,  2881,  2948,  3015,  3082, 
     2747,  3149,  3216,  2747,  3283,  3350,  1541,  3417,  3484,  3551, 
     3618,  3685,  3752,  3819,  3886,  3953,  4020,  4087,  4154,  4221, 
     4288,  4355,  1541,  4422,  1541,  4489,  4556,  1541,  1541,  1541, 
     1541,  1541,  1541,  4623,  4690,  4757,  4824,  4891,  4958,  5025, 
     1541,  1541,  5092,  1541,  5159,  1541,  1541,  1541,  1541,  1541, 
     1541,  5226,  5293,  5360,  5427,  5494,  5561,  5628,  5695,  5762, 
     5829,  5896,   134,  5963,  6030,  6097,  6164,  6231,  6298,  6365, 
     6432,  6499,  6566,  6633,  2747,  6700,  6767,  6834,  6901,  6968, 
     7035,   134,  7102,  7169,  7236,  7303,  7370,  7437,   134,  7504, 
     7571,  7638,   134,  7705,  7772,  7839,  7906,  1541,  7973,  8040, 
     8107,  8174,  8241,  8308,  8375,  8442,  8509,  8576,  8643,  8710, 
     8777,  1541,  8844,  1541,  1541,  8911,  1541,  1541,  8978,  1541, 
     9045,  9112,  9179,  9246,  9313,  9380,  9447,  9514,  9581,  9648, 
     9715,  9782,  9849,  9916,  9983, 10050, 10117, 10184, 10251, 10318, 
    10385, 10452, 10519, 10586, 10653, 10720,  2747, 10787, 10854, 10921, 
      134, 10988, 11055, 11122,   134, 11189, 11256,   134, 11323, 11390, 
      134, 11457,  1541, 11524, 11591, 11658, 11725,  1541,   134,   134, 
    11792, 11859, 11926,  1541, 11993, 12060, 12127, 12194, 12261, 12328, 
    12395, 12462, 12529,   134, 12596, 12663,   134, 12730, 12797, 12864, 
    12931,   134, 12998, 13065, 13132, 13199, 13266,   134, 13333, 13400, 
      134, 13467, 13534, 13601,   134, 13668,   134, 13735, 13802, 13869, 
    13936, 14003, 14070,  1541, 14137, 14204, 14271, 14338,   134, 14405, 
    14472, 14539,   134, 14606,   134,   134, 14673,   134, 14740, 14807, 
    14874, 14941, 15008, 15075, 15142, 15209, 15276,   134, 15343,   134, 
      134, 15410, 15477, 15544,   134, 15611, 15678, 15745, 15812, 15879, 
      134, 15946, 16013,   134, 16080,   134, 16147, 16214, 16281, 16348, 
      134,   134, 16415, 16482, 16549, 16616,   134,   134,   134, 16683, 
    16750,   134,   134, 16817, 16884, 16951, 17018, 17085, 17152, 17219, 
    17286,   134,   134, 17353, 17420, 17487,   134,   134, 17554,   134, 
    17621, 17688, 17755, 17822,   134,   134, 17889,   134, 17956, 18023, 
      134, 18090,   134,   134, 18157,   134
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\2\4\1\5\1\4\1\3\1\6\1\7"+
    "\1\6\1\10\1\3\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\3\3"+
    "\1\25\2\3\1\26\1\3\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\4\3\1\55\1\56\1\3\1\57\1\60"+
    "\1\61\1\62\1\63\1\3\7\2\1\0\1\2\2\0"+
    "\6\2\6\0\11\2\23\0\21\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\20\3\2\64\4\4"+
    "\1\64\1\0\1\64\2\0\4\64\1\65\1\64\6\0"+
    "\2\66\2\64\2\67\1\65\2\70\1\71\22\0\22\64"+
    "\1\72\1\73\1\74\1\73\1\64\1\0\1\64\2\0"+
    "\4\64\1\75\1\64\6\0\2\66\2\76\2\77\1\75"+
    "\2\100\1\101\22\0\20\64\7\0\1\6\1\0\1\6"+
    "\71\0\7\2\1\0\1\2\2\0\1\102\5\2\6\0"+
    "\11\2\23\0\20\2\51\0\1\103\31\0\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\4\3\1\104\4\3"+
    "\23\0\20\3\1\2\6\3\1\0\1\7\2\0\1\105"+
    "\5\3\6\0\4\3\1\106\4\3\23\0\1\107\17\3"+
    "\1\2\6\3\1\0\1\7\2\0\1\3\1\110\4\3"+
    "\6\0\11\3\23\0\3\3\1\111\1\3\1\112\12\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\1\113"+
    "\10\3\23\0\1\114\2\3\1\115\3\3\1\116\10\3"+
    "\1\2\6\3\1\0\1\7\2\0\1\3\1\117\4\3"+
    "\6\0\11\3\23\0\6\3\1\120\11\3\10\121\1\122"+
    "\1\0\7\121\1\123\61\121\10\17\1\124\1\0\10\17"+
    "\1\125\60\17\23\0\1\126\1\127\24\0\1\130\102\0"+
    "\1\131\56\0\1\132\23\0\1\133\57\0\1\134\22\0"+
    "\1\135\31\0\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\11\3\23\0\3\3\1\136\14\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\1\137\1\3\1\140"+
    "\6\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\4\3\1\141\4\3\23\0\3\3\1\142"+
    "\14\3\2\0\2\143\1\144\1\143\251\0\1\145\102\0"+
    "\1\146\1\147\101\0\1\150\1\0\1\151\100\0\1\152"+
    "\102\0\1\153\6\0\1\154\73\0\1\155\7\0\1\156"+
    "\72\0\1\157\31\0\1\2\6\3\1\0\1\7\2\0"+
    "\3\3\1\160\2\3\6\0\11\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\1\161\4\3\1\162\6\0"+
    "\11\3\23\0\5\3\1\163\1\164\5\3\1\165\3\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\1\166"+
    "\10\3\23\0\1\167\2\3\1\170\2\3\1\171\11\3"+
    "\1\2\6\3\1\0\1\7\2\0\2\3\1\172\1\3"+
    "\1\173\1\3\6\0\11\3\23\0\11\3\1\174\6\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\3\3\1\175\14\3\1\2\6\3\1\0\1\7"+
    "\2\0\1\176\1\177\4\3\6\0\11\3\23\0\1\200"+
    "\17\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\3\3\1\201\14\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\11\3\23\0\6\3\1\202"+
    "\11\3\1\2\6\3\1\0\1\7\2\0\5\3\1\203"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\1\204\17\3\7\64"+
    "\1\0\1\64\2\0\6\64\6\0\12\64\22\0\22\64"+
    "\4\205\1\64\1\0\1\64\2\0\6\64\4\0\2\206"+
    "\12\64\22\0\22\64\4\71\1\64\1\0\1\64\2\0"+
    "\4\64\1\65\1\64\6\0\4\64\2\67\1\65\2\70"+
    "\1\64\22\0\22\64\4\72\1\64\1\0\1\64\2\0"+
    "\4\64\1\65\1\64\6\0\4\64\2\67\1\65\2\70"+
    "\1\71\22\0\22\64\1\72\3\73\1\64\1\0\1\64"+
    "\2\0\4\64\1\65\1\64\6\0\2\207\2\64\2\67"+
    "\1\65\2\70\1\71\22\0\22\64\1\72\1\73\1\74"+
    "\1\73\1\64\1\0\1\64\2\0\4\64\1\75\1\64"+
    "\6\0\2\207\2\64\2\77\1\75\2\100\1\101\22\0"+
    "\21\64\5\210\1\64\1\0\1\64\2\0\3\64\2\210"+
    "\1\64\6\0\4\64\5\210\1\64\22\0\1\210\1\64"+
    "\1\210\17\64\4\211\1\64\1\0\1\64\2\0\6\64"+
    "\4\0\2\212\12\64\22\0\22\64\2\71\1\101\1\71"+
    "\1\64\1\0\1\64\2\0\4\64\1\75\1\64\6\0"+
    "\4\64\2\77\1\75\2\100\1\64\22\0\20\64\1\2"+
    "\5\213\1\2\1\0\1\2\2\0\3\2\2\213\1\2"+
    "\6\0\4\2\5\213\23\0\1\213\1\2\1\213\16\2"+
    "\6\3\1\0\1\7\2\0\5\3\1\214\6\0\11\3"+
    "\23\0\20\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\1\215\10\3\23\0\20\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\11\3\23\0\14\3\1\216"+
    "\3\3\1\2\6\3\1\0\1\7\2\0\5\3\1\217"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\4\3\1\220\4\3\23\0\20\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\3\3\1\221\14\3\1\2\6\3\1\0\1\7"+
    "\2\0\5\3\1\222\6\0\11\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\3\3\1\223\14\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\1\224\10\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\1\3\1\225\4\3\6\0\11\3"+
    "\23\0\20\3\1\2\6\3\1\0\1\7\2\0\2\3"+
    "\1\226\3\3\6\0\11\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\1\227\5\3\6\0\11\3\23\0"+
    "\1\230\4\3\1\231\12\3\1\2\6\3\1\0\1\7"+
    "\2\0\1\3\1\232\4\3\6\0\11\3\23\0\7\3"+
    "\1\233\10\3\10\234\1\235\1\0\7\234\1\236\64\234"+
    "\1\237\2\240\2\234\1\121\1\0\1\234\1\241\7\121"+
    "\60\234\3\242\3\17\2\242\1\17\1\0\1\242\1\243"+
    "\6\17\1\244\60\242\11\126\1\0\71\126\24\245\1\246"+
    "\56\245\1\2\6\3\1\0\1\7\2\0\2\3\1\247"+
    "\3\3\6\0\11\3\23\0\20\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\11\3\23\0\1\3\1\250"+
    "\16\3\1\2\6\3\1\0\1\7\2\0\5\3\1\251"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\4\3\1\252\1\3\6\0\11\3\23\0\20\3"+
    "\1\2\6\3\1\0\1\7\2\0\1\253\5\3\6\0"+
    "\11\3\23\0\20\3\2\0\4\143\11\0\1\254\13\0"+
    "\2\255\1\254\2\256\45\0\2\143\1\144\1\143\11\0"+
    "\1\257\13\0\2\260\1\257\2\261\114\0\1\262\1\263"+
    "\101\0\1\264\31\0\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\11\3\23\0\1\3\1\265\16\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\12\3\1\266\5\3\1\2\6\3\1\0\1\7\2\0"+
    "\1\3\1\267\4\3\6\0\11\3\23\0\1\270\17\3"+
    "\1\2\6\3\1\0\1\7\2\0\2\3\1\271\3\3"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\3\3\1\272\14\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\7\3\1\273\10\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\1\274\17\3\1\2"+
    "\6\3\1\0\1\7\2\0\5\3\1\275\6\0\11\3"+
    "\23\0\1\3\1\276\16\3\1\2\6\3\1\0\1\7"+
    "\2\0\2\3\1\277\3\3\6\0\11\3\23\0\20\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\1\300\17\3\1\2\6\3\1\0\1\7\2\0"+
    "\5\3\1\301\6\0\11\3\23\0\1\3\1\302\16\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\12\3\1\303\5\3\1\2\6\3\1\0\1\7"+
    "\2\0\5\3\1\304\6\0\11\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\3\3\1\305\2\3\6\0"+
    "\11\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\11\3\23\0\3\3\1\306\3\3\1\307"+
    "\10\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\2\3\1\310\15\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\1\311\10\3\23\0\7\3"+
    "\1\312\10\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\11\3\23\0\7\3\1\313\10\3\1\2\6\3"+
    "\1\0\1\7\2\0\1\3\1\314\4\3\6\0\11\3"+
    "\23\0\20\3\1\2\6\3\1\0\1\7\2\0\5\3"+
    "\1\315\6\0\11\3\23\0\20\3\2\64\4\205\1\64"+
    "\1\0\1\64\2\0\4\64\1\65\1\64\6\0\6\64"+
    "\1\65\2\70\1\64\22\0\20\64\2\0\4\316\75\0"+
    "\1\64\5\210\1\64\1\0\1\64\2\0\3\64\2\210"+
    "\1\64\6\0\2\317\2\64\5\210\1\64\22\0\1\210"+
    "\1\64\1\210\17\64\4\211\1\64\1\0\1\64\2\0"+
    "\4\64\1\75\1\64\6\0\6\64\1\75\2\100\1\64"+
    "\22\0\20\64\2\0\4\320\75\0\1\2\5\321\1\2"+
    "\1\0\1\2\2\0\3\2\2\321\1\2\6\0\4\2"+
    "\5\321\23\0\1\321\1\2\1\321\16\2\6\3\1\0"+
    "\1\7\2\0\1\322\5\3\6\0\11\3\23\0\20\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\1\323"+
    "\10\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\11\3\23\0\7\3\1\324\10\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\1\325\17\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\1\326\10\3\23\0\20\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\4\3\1\327\4\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\1\330\17\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\1\3\1\227\16\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\1\331\17\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\4\3\1\332\4\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\2\3\1\333\3\3\6\0"+
    "\11\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\11\3\23\0\3\3\1\334\14\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\1\3\1\335\16\3\10\234\1\235\1\0\7\234\1\123"+
    "\72\234\1\0\74\234\3\121\2\234\1\235\1\0\7\234"+
    "\1\236\64\234\3\237\2\234\1\235\1\0\7\234\1\236"+
    "\62\234\5\336\2\234\1\235\1\0\4\234\2\336\1\234"+
    "\1\123\11\234\5\336\23\234\1\336\1\234\1\336\15\234"+
    "\11\242\1\0\10\242\1\337\61\242\5\340\3\242\1\0"+
    "\4\242\2\340\2\242\1\337\10\242\5\340\23\242\1\340"+
    "\1\242\1\340\15\242\10\244\1\341\1\0\10\244\1\125"+
    "\60\244\24\245\1\342\56\245\23\343\1\344\1\246\56\343"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\10\3\1\345\7\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\4\3\1\346\4\3\23\0\20\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\4\3"+
    "\1\347\4\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\1\350\17\3\1\2"+
    "\6\3\1\0\1\7\2\0\3\3\1\351\2\3\6\0"+
    "\11\3\23\0\20\3\2\0\4\316\17\0\2\206\56\0"+
    "\4\320\17\0\2\212\125\0\1\352\31\0\1\2\6\3"+
    "\1\0\1\7\2\0\5\3\1\353\6\0\11\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\4\3\1\354\4\3\23\0\20\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\11\3\23\0\7\3\1\355"+
    "\10\3\1\2\6\3\1\0\1\7\2\0\5\3\1\356"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\2\3\1\357\15\3"+
    "\1\2\6\3\1\0\1\7\2\0\1\3\1\360\4\3"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\5\3\1\361\6\0\11\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\1\3\1\362\16\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\11\3\23\0\2\3\1\363\15\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\4\3\1\364"+
    "\4\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\5\3\1\365\6\0\11\3\23\0\1\3\1\366\16\3"+
    "\1\2\6\3\1\0\1\7\2\0\1\3\1\367\4\3"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\4\3\1\370\4\3\23\0\20\3"+
    "\1\2\6\3\1\0\1\7\2\0\5\3\1\371\6\0"+
    "\11\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\1\372\10\3\23\0\3\3\1\373\14\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\3\3\1\374\14\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\1\375\10\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\5\3\1\376\6\0\11\3"+
    "\23\0\20\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\11\3\23\0\13\3\1\377\4\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\11\3\23\0\4\3"+
    "\1\u0100\13\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\11\3\23\0\1\u0101\17\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\7\3\1\u0102\1\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\1\u0103\10\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\7\3\1\u0104\10\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\6\3\1\u0105\11\3\2\0\4\316\11\0\1\254"+
    "\15\0\1\254\2\256\45\0\4\320\11\0\1\257\15\0"+
    "\1\257\2\261\43\0\1\2\5\u0106\1\2\1\0\1\2"+
    "\2\0\3\2\2\u0106\1\2\6\0\4\2\5\u0106\23\0"+
    "\1\u0106\1\2\1\u0106\16\2\6\3\1\0\1\7\2\0"+
    "\1\3\1\u0107\4\3\6\0\11\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\13\3\1\u0108\4\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\11\3\23\0\4\3\1\u0109\13\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\4\3\1\u010a"+
    "\4\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\5\3\1\u010b\6\0\11\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\1\u010c\10\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\1\3\1\u010d\16\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\11\3\23\0\14\3\1\u010e"+
    "\3\3\1\234\5\u010f\2\234\1\235\1\0\4\234\2\u010f"+
    "\1\234\1\123\11\234\5\u010f\23\234\1\u010f\1\234\1\u010f"+
    "\15\234\1\242\5\u0110\3\242\1\0\4\242\2\u0110\2\242"+
    "\1\337\10\242\5\u0110\23\242\1\u0110\1\242\1\u0110\15\242"+
    "\3\0\3\244\2\0\1\244\2\0\1\u0111\7\244\60\0"+
    "\23\245\1\u0112\1\342\56\245\24\343\1\246\56\343\1\2"+
    "\6\3\1\0\1\7\2\0\2\3\1\u0113\3\3\6\0"+
    "\11\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\1\u0114\5\3\6\0\11\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\1\u0115\10\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\1\3\1\u0116"+
    "\4\3\6\0\11\3\23\0\20\3\1\2\6\3\1\0"+
    "\1\7\2\0\1\3\1\u0117\4\3\6\0\11\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\2\3\1\u0118\15\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\11\3\23\0\7\3\1\u0119"+
    "\10\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\6\3\1\u011a\11\3\1\2\6\3\1\0"+
    "\1\7\2\0\5\3\1\u011b\6\0\11\3\23\0\20\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\2\3\1\u011c\15\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\1\3\1\u011d\16\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\6\3\1\u011e\11\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\7\3\1\u011f\10\3"+
    "\1\2\6\3\1\0\1\7\2\0\5\3\1\u0120\6\0"+
    "\11\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\1\3\1\u0121\4\3\6\0\11\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\1\u0122\17\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\4\3\1\u0123\4\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\1\3\1\u0124\4\3\6\0\11\3"+
    "\23\0\20\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\11\3\23\0\7\3\1\u0125\10\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\4\3\1\u0126\4\3"+
    "\23\0\20\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\11\3\23\0\1\u0127\17\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\11\3\23\0\1\u0128\17\3"+
    "\1\2\6\3\1\0\1\7\2\0\5\3\1\u0129\6\0"+
    "\11\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\4\3\1\u012a\4\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\2\3\1\u012b\3\3\6\0"+
    "\11\3\23\0\20\3\1\2\5\3\1\2\1\0\1\2"+
    "\2\0\3\2\2\3\1\2\6\0\4\2\5\3\23\0"+
    "\1\3\1\2\1\3\16\2\6\3\1\0\1\7\2\0"+
    "\2\3\1\u012c\3\3\6\0\11\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\4\3\1\u012d"+
    "\4\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\11\3\23\0\1\u012e\17\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\1\u012f\10\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\7\3\1\u0130\10\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\11\3\23\0\1\3\1\u0131"+
    "\16\3\1\234\5\u0132\2\234\1\235\1\0\4\234\2\u0132"+
    "\1\234\1\123\11\234\5\u0132\23\234\1\u0132\1\234\1\u0132"+
    "\15\234\1\242\5\u0133\3\242\1\0\4\242\2\u0133\2\242"+
    "\1\337\10\242\5\u0133\23\242\1\u0133\1\242\1\u0133\15\242"+
    "\1\0\5\u0134\10\0\2\u0134\13\0\5\u0134\23\0\1\u0134"+
    "\1\0\1\u0134\15\0\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\7\3\1\u0135\1\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\1\u0136\10\3"+
    "\23\0\20\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\4\3\1\u0137\4\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\11\3\23\0\1\u0138"+
    "\17\3\1\2\6\3\1\0\1\7\2\0\5\3\1\u0139"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\2\3\1\u013a\15\3"+
    "\1\2\6\3\1\0\1\7\2\0\1\3\1\u013b\4\3"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\6\3\1\u013c\11\3"+
    "\1\2\6\3\1\0\1\7\2\0\2\3\1\u013d\3\3"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\4\3\1\u013e\1\3\6\0\11\3\23\0\20\3"+
    "\1\2\6\3\1\0\1\7\2\0\2\3\1\u013f\3\3"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\11\3\23\0\11\3\1\u0140\6\3"+
    "\1\2\6\3\1\0\1\7\2\0\5\3\1\u0141\6\0"+
    "\11\3\23\0\20\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\11\3\23\0\2\3\1\u0142\15\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\2\3\1\u0143\15\3\1\2\6\3\1\0\1\7\2\0"+
    "\5\3\1\u0144\6\0\11\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\11\3\23\0\10\3"+
    "\1\u0145\7\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\11\3\23\0\7\3\1\u0146\10\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\11\3\23\0\10\3"+
    "\1\u0147\7\3\1\2\6\3\1\0\1\7\2\0\2\3"+
    "\1\u0148\3\3\6\0\11\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\11\3\23\0\5\3"+
    "\1\u0149\12\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\4\3\1\u014a\4\3\23\0\20\3\1\234\5\121"+
    "\2\234\1\235\1\0\4\234\2\121\1\234\1\123\11\234"+
    "\5\121\23\234\1\121\1\234\1\121\15\234\1\242\5\17"+
    "\3\242\1\0\4\242\2\17\2\242\1\337\10\242\5\17"+
    "\23\242\1\17\1\242\1\17\15\242\1\0\5\u014b\10\0"+
    "\2\u014b\13\0\5\u014b\23\0\1\u014b\1\0\1\u014b\15\0"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\11\3"+
    "\23\0\1\3\1\u014c\16\3\1\2\6\3\1\0\1\7"+
    "\2\0\5\3\1\u014d\6\0\11\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\2\3\1\u014e\15\3\1\2\6\3\1\0\1\7\2\0"+
    "\4\3\1\u014f\1\3\6\0\11\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\3\3\1\u0150\14\3\1\2\6\3\1\0\1\7\2\0"+
    "\1\u0151\5\3\6\0\11\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\11\3\23\0\1\u0152"+
    "\17\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\2\3\1\u0153\15\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\4\3\1\u0154\4\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\5\3\1\u0155"+
    "\6\0\11\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\4\3\1\u0156\4\3\23\0\20\3"+
    "\1\2\6\3\1\0\1\7\2\0\6\3\6\0\4\3"+
    "\1\u0157\4\3\23\0\20\3\1\2\6\3\1\0\1\7"+
    "\2\0\6\3\6\0\1\u0158\10\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\2\3\1\u0159\3\3\6\0"+
    "\11\3\23\0\20\3\1\0\5\u015a\10\0\2\u015a\13\0"+
    "\5\u015a\23\0\1\u015a\1\0\1\u015a\15\0\1\2\6\3"+
    "\1\0\1\7\2\0\5\3\1\u015b\6\0\11\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\12\3\1\u015c\5\3\1\2\6\3\1\0"+
    "\1\7\2\0\2\3\1\u015d\3\3\6\0\11\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\4\3\1\u015e\4\3\23\0\20\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\11\3\23\0\2\3\1\u015f"+
    "\15\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\4\3\1\u0160\4\3\23\0\20\3\1\2\6\3\1\0"+
    "\1\7\2\0\2\3\1\u0161\3\3\6\0\11\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\4\3\1\u0162\4\3\23\0\20\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\4\3\1\u0163\4\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\5\3\1\u0164"+
    "\6\0\11\3\23\0\20\3\1\0\5\244\10\0\2\244"+
    "\13\0\5\244\23\0\1\244\1\0\1\244\15\0\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\7\3\1\u0165\10\3\1\2\6\3\1\0\1\7\2\0"+
    "\6\3\6\0\4\3\1\u0166\4\3\23\0\20\3\1\2"+
    "\6\3\1\0\1\7\2\0\6\3\6\0\11\3\23\0"+
    "\3\3\1\u0167\14\3\1\2\6\3\1\0\1\7\2\0"+
    "\5\3\1\u0168\6\0\11\3\23\0\20\3\1\2\6\3"+
    "\1\0\1\7\2\0\6\3\6\0\7\3\1\u0169\1\3"+
    "\23\0\20\3\1\2\6\3\1\0\1\7\2\0\6\3"+
    "\6\0\11\3\23\0\17\3\1\u016a\1\2\6\3\1\0"+
    "\1\7\2\0\4\3\1\u016b\1\3\6\0\11\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\11\3\23\0\1\3\1\u016c\16\3\1\2\6\3\1\0"+
    "\1\7\2\0\6\3\6\0\4\3\1\u016d\4\3\23\0"+
    "\20\3\1\2\6\3\1\0\1\7\2\0\6\3\6\0"+
    "\7\3\1\u016e\1\3\23\0\20\3";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9,  9,  9,  9,  1, 
     1,  1,  1,  9,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  0,  9,  1,  9,  1,  1,  9,  9,  9,  9,  9,  9,  1,  1,  1, 
     1,  1,  1,  1,  9,  9,  1,  9,  1,  9,  9,  9,  9,  9,  9,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  0,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  9,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  0,  9,  9,  0, 
     9,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1, 
     0,  1,  1,  9,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     0,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /* user code: */
    private int lastToken;
    private int nextState=YYINITIAL;
    
    /** 
     * next Token method that allows you to control if whitespace and comments are
     * returned as tokens.
     */
    public Token getNextToken(boolean returnComments, boolean returnWhiteSpace)throws IOException{
        Token t = getNextToken();
        while (t != null && ((!returnWhiteSpace && t.isWhiteSpace()) || (!returnComments && t.isComment()))){
            t = getNextToken();
        }
        return (t); 
    }
        
    /**
     * Prints out tokens from a file or System.in.
     * If no arguments are given, System.in will be used for input.
     * If more arguments are given, the first argument will be used as
     * the name of the file to use as input
     *
     * @param args program arguments, of which the first is a filename
     */
    public static void main(String[] args) {
        InputStream in;
        try {
            if (args.length > 0){
                File f = new File(args[0]);
                if (f.exists()){
                    if (f.canRead()){
                        in = new FileInputStream(f);
                    } else {
                        throw new IOException("Could not open " + args[0]);
                    }
                } else {
                    throw new IOException("Could not find " + args[0]);
                }
            } else {
                in = System.in;
            }
            JavaLexer shredder = new JavaLexer(in);
            Token t;
            while ((t = shredder.getNextToken()) != null) {
                if (t.getID() != JavaToken.WHITE_SPACE){
                    System.out.println(t);
                }
            }
        } catch (IOException e){
            System.out.println(e.getMessage());
        }
    }  

    /**
     * Closes the current input stream, and resets the scanner to read from a new input stream.
	 * All internal variables are reset, the old input stream  cannot be reused
	 * (content of the internal buffer is discarded and lost).
	 * The lexical state is set to the initial state.
     * Subsequent tokens read from the lexer will start with the line, char, and column
     * values given here.
     *
     * @param reader The new input.
     * @param yyline The line number of the first token.
     * @param yychar The position (relative to the start of the stream) of the first token.
     * @param yycolumn The position (relative to the line) of the first token.
     * @throws IOException if an IOExecption occurs while switching readers.
     */
    public void reset(java.io.Reader reader, int yyline, int yychar, int yycolumn) throws IOException{
        yyreset(reader);
        this.yyline = yyline;
		this.yychar = yychar;
		this.yycolumn = yycolumn;
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JavaLexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public JavaLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[18224];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public Token getNextToken() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
          }
          break;
        default:
          yy_r = false;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 210: 
          {  
    lastToken = JavaToken.LITERAL_NULL;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 367: break;
        case 51: 
        case 54: 
        case 57: 
        case 61: 
        case 62: 
          {  
    lastToken = JavaToken.ERROR_FLOAT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 368: break;
        case 5: 
          {  
    lastToken = JavaToken.WHITE_SPACE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 369: break;
        case 23: 
          {  
    lastToken = JavaToken.SEPARATOR_LPAREN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
     }
        case 370: break;
        case 365: 
          {  
    lastToken = JavaToken.RESERVED_WORD_SYNCHRONIZED;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 371: break;
        case 179: 
          {  
    lastToken = JavaToken.OPERATOR_SHIFT_LEFT_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 372: break;
        case 82: 
          {  
    lastToken = JavaToken.ERROR_MALFORMED_CHARACTER;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 373: break;
        case 108: 
          {  
    lastToken = JavaToken.OPERATOR_BITWISE_OR_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 374: break;
        case 233: 
          {  
    lastToken = JavaToken.OPERATOR_SHIFT_RIGHT_UNSIGNED_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 375: break;
        case 217: 
          {  
    lastToken = JavaToken.LITERAL_BOOLEAN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 376: break;
        case 1: 
        case 6: 
        case 65: 
        case 138: 
        case 208: 
        case 261: 
          {  
    lastToken = JavaToken.ERROR_IDENTIFIER;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 377: break;
        case 97: 
          {  
    lastToken = JavaToken.RESERVED_WORD_DO;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 378: break;
        case 101: 
          {  
    lastToken = JavaToken.OPERATOR_GREATER_THAN_OR_EQUAL;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 379: break;
        case 122: 
          {  
    lastToken = JavaToken.RESERVED_WORD_IF;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 380: break;
        case 178: 
          {  
    lastToken = JavaToken.OPERATOR_SHIFT_RIGHT_UNSIGNED;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 381: break;
        case 13: 
        case 155: 
        case 160: 
        case 221: 
        case 270: 
        case 305: 
          {  
    lastToken = JavaToken.ERROR_MALFORMED_UNCLOSED_CHARACTER;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 382: break;
        case 83: 
        case 161: 
        case 162: 
        case 223: 
        case 271: 
        case 306: 
          {  
    lastToken = JavaToken.ERROR_MALFORMED_UNCLOSED_STRING;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 383: break;
        case 84: 
          {  
    lastToken = JavaToken.LITERAL_STRING;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 384: break;
        case 53: 
          {  
    String text = yytext();
    try {
        if (lastToken == JavaToken.OPERATOR_SUBTRACT){
            Long.decode('-' + text.substring(0,text.length()-1));
        } else {
            Long.decode(text.substring(0,text.length()-1));
        }
        lastToken = JavaToken.LITERAL_LONG_DECIMAL;
    } catch (NumberFormatException e){  
        lastToken = JavaToken.ERROR_LONG_DECIMIAL_SIZE;
    }
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 385: break;
        case 7: 
          { 
    lastToken = JavaToken.OPERATOR_MOD;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 386: break;
        case 17: 
          { 
    lastToken = JavaToken.OPERATOR_ADD;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 387: break;
        case 35: 
          { 
    lastToken = JavaToken.OPERATOR_BITWISE_COMPLIMENT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 388: break;
        case 326: 
          { 
    lastToken = JavaToken.CLASS_LANG_STRING;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 389: break;
        case 36: 
          { 
    lastToken = JavaToken.OPERATOR_QUESTION;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 390: break;
        case 16: 
          { 
    lastToken = JavaToken.OPERATOR_MULTIPLY;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 391: break;
        case 18: 
          { 
    lastToken = JavaToken.OPERATOR_SUBTRACT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 392: break;
        case 22: 
          { 
    lastToken = JavaToken.SEPARATOR_PERIOD;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 393: break;
        case 24: 
          { 
    lastToken = JavaToken.SEPARATOR_RPAREN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 394: break;
        case 25: 
          { 
    lastToken = JavaToken.SEPARATOR_LBRACE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 395: break;
        case 26: 
          { 
    lastToken = JavaToken.SEPARATOR_RBRACE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 396: break;
        case 148: 
          { 
    lastToken = JavaToken.RESERVED_WORD_FOR;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 397: break;
        case 206: 
          { 
    /* A Hex long cannot be too big.  After removing 
     * initial zeros, It can have 17 digits, the last of which is
     * the L or l
     */
    lastToken = JavaToken.LITERAL_LONG_HEXIDECIMAL;
    int i;
    String text = yytext();
    int length = text.length();
    for (i=2 ; i<length-17; i++){
        //check for initial zeros
        if (text.charAt(i) != '0'){ 
            lastToken = JavaToken.ERROR_LONG_HEXIDECIMAL_SIZE;
        }
    }
    if (length - i > 17){
        lastToken = JavaToken.ERROR_LONG_HEXIDECIMAL_SIZE;
    }
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 398: break;
        case 135: 
          { 
    /* A Hex number cannot be too big.  After removing 
     * initial zeros, It can have 8 digits
     */
    lastToken = JavaToken.LITERAL_INTEGER_HEXIDECIMAL;
    int i;    
    String text = yytext();
    int length = text.length();
    for (i=2 ; i<length-8; i++){
        //check for initial zeros
        if (text.charAt(i) != '0'){ 
            lastToken = JavaToken.ERROR_INTEGER_HEXIDECIMAL_SIZE;
        }
    }
    if (length - i > 8){
        lastToken = JavaToken.ERROR_INTEGER_HEXIDECIMAL_SIZE;
    }
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 399: break;
        case 260: 
          { 
    lastToken = JavaToken.CLASS_LANG_MATH;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 400: break;
        case 37: 
          { 
    lastToken = JavaToken.OPERATOR_COLON;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 401: break;
        case 31: 
          { 
    lastToken = JavaToken.OPERATOR_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 402: break;
        case 30: 
          { 
    lastToken = JavaToken.SEPARATOR_COMMA;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 403: break;
        case 15: 
          { 
    lastToken = JavaToken.OPERATOR_DIVIDE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 404: break;
        case 63: 
        case 64: 
        case 99: 
        case 136: 
        case 176: 
        case 207: 
          { 
    lastToken = JavaToken.LITERAL_DOUBLE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 405: break;
        case 100: 
          { 
    lastToken = JavaToken.OPERATOR_EQUAL;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 406: break;
        case 58: 
        case 59: 
          { 
    /* An Octal number cannot be too big.  After removing 
     * initial zeros, It can have 11 digits, the first
     * of which must be 3 or less.
     */
    lastToken = JavaToken.LITERAL_INTEGER_OCTAL;
    int i;     
    String text = yytext();
    int length = text.length();
    for (i=1 ; i<length-11; i++){
        //check for initial zeros
        if (yytext().charAt(i) != '0'){ 
            lastToken = JavaToken.ERROR_INTEGER_OCTAL_SIZE;
        }
    }
    if (length - i > 11){
        lastToken = JavaToken.ERROR_INTEGER_OCTAL_SIZE;
    } else if (length - i == 11){
        // if the rest of the number is as big as possible
        // the first digit can only be 3 or less
        if (text.charAt(i) != '0' && text.charAt(i) != '1' && 
        text.charAt(i) != '2' && text.charAt(i) != '3'){
            lastToken = JavaToken.ERROR_INTEGER_OCTAL_SIZE;
        }
    }
    // Otherwise, it should be OK  
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 407: break;
        case 354: 
          {  
    lastToken = JavaToken.RESERVED_WORD_VOLATILE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 408: break;
        case 349: 
          {  
    lastToken = JavaToken.RESERVED_WORD_CONTINUE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 409: break;
        case 346: 
          {  
    lastToken = JavaToken.RESERVED_WORD_ABSTRACT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 410: break;
        case 342: 
          {  
    lastToken = JavaToken.RESERVED_WORD_PACKAGE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 411: break;
        case 341: 
          {  
    lastToken = JavaToken.RESERVED_WORD_PRIVATE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 412: break;
        case 332: 
          {  
    lastToken = JavaToken.RESERVED_WORD_DEFAULT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 413: break;
        case 331: 
          {  
    lastToken = JavaToken.RESERVED_WORD_EXTENDS;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 414: break;
        case 328: 
          {  
    lastToken = JavaToken.RESERVED_WORD_FINALLY;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 415: break;
        case 327: 
          {  
    lastToken = JavaToken.RESERVED_WORD_BOOLEAN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 416: break;
        case 222: 
          {  
    lastToken = JavaToken.ERROR_MALFORMED_STRING;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 417: break;
        case 86: 
        case 164: 
        case 165: 
        case 225: 
        case 226: 
          {  
    lastToken = JavaToken.ERROR_UNCLOSED_COMMENT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 418: break;
        case 87: 
          {  
    lastToken = JavaToken.OPERATOR_DIVIDE_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 419: break;
        case 60: 
        case 174: 
          { 
    /* catch the case of a zero in parsing, so that we do not incorrectly
     * give an error that a number was rounded to zero
     */
    lastToken = JavaToken.LITERAL_FLOATING_POINT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 420: break;
        case 257: 
          {  
    lastToken = JavaToken.RESERVED_WORD_VOID;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 421: break;
        case 251: 
          {  
    lastToken = JavaToken.RESERVED_WORD_GOTO;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 422: break;
        case 246: 
          {  
    lastToken = JavaToken.RESERVED_WORD_CHAR;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 423: break;
        case 243: 
          {  
    lastToken = JavaToken.RESERVED_WORD_CASE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 424: break;
        case 229: 
          {  
    lastToken = JavaToken.RESERVED_WORD_ELSE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 425: break;
        case 228: 
          {  
    lastToken = JavaToken.RESERVED_WORD_LONG;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 426: break;
        case 220: 
          {  
    lastToken = JavaToken.RESERVED_WORD_THIS;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 427: break;
        case 214: 
          {  
    lastToken = JavaToken.RESERVED_WORD_BYTE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 428: break;
        case 192: 
          {  
    lastToken = JavaToken.RESERVED_WORD_INT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 429: break;
        case 89: 
          {  
    lastToken = JavaToken.OPERATOR_INCREMENT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 430: break;
        case 91: 
          {  
    lastToken = JavaToken.OPERATOR_DECREMENT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 431: break;
        case 105: 
          {  
    lastToken = JavaToken.OPERATOR_NOT_EQUAL;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 432: break;
        case 141: 
          {  
    lastToken = JavaToken.RESERVED_WORD_NEW;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 433: break;
        case 152: 
          {  
    lastToken = JavaToken.RESERVED_WORD_TRY;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 434: break;
        case 157: 
          {  
    lastToken = JavaToken.LITERAL_CHARACTER;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 435: break;
        case 347: 
          { 
    lastToken = JavaToken.RESERVED_WORD_STRICTFP;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 436: break;
        case 55: 
        case 56: 
        case 98: 
        case 132: 
        case 173: 
        case 205: 
          { 
    Double d;
    try {
        d = Double.valueOf(yytext());
        if (d.isInfinite() || d.compareTo(new Double(0d)) == 0){
            lastToken = JavaToken.ERROR_DOUBLE_SIZE;
        } else {
            lastToken = JavaToken.LITERAL_DOUBLE;
        }
    } catch (NumberFormatException e){
        lastToken = JavaToken.ERROR_DOUBLE_SIZE;
    } 
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 437: break;
        case 363: 
          {  
    lastToken = JavaToken.RESERVED_WORD_IMPLEMENTS;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 438: break;
        case 362: 
          {  
    lastToken = JavaToken.RESERVED_WORD_INSTANCEOF;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 439: break;
        case 360: 
          {  
    lastToken = JavaToken.RESERVED_WORD_PROTECTED;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 440: break;
        case 357: 
          {  
    lastToken = JavaToken.RESERVED_WORD_INTERFACE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 441: break;
        case 355: 
          {  
    lastToken = JavaToken.RESERVED_WORD_TRANSIENT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 442: break;
        case 321: 
          {  
    lastToken = JavaToken.RESERVED_WORD_PUBLIC;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 443: break;
        case 320: 
          {  
    lastToken = JavaToken.RESERVED_WORD_IMPORT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 444: break;
        case 315: 
          {  
    lastToken = JavaToken.RESERVED_WORD_SWITCH;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 445: break;
        case 310: 
          {  
    lastToken = JavaToken.RESERVED_WORD_DOUBLE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 446: break;
        case 304: 
          {  
    lastToken = JavaToken.RESERVED_WORD_THROWS;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 447: break;
        case 300: 
          {  
    lastToken = JavaToken.RESERVED_WORD_NATIVE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 448: break;
        case 299: 
          {  
    lastToken = JavaToken.RESERVED_WORD_RETURN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 449: break;
        case 297: 
          {  
    lastToken = JavaToken.RESERVED_WORD_WHILE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 450: break;
        case 287: 
          {  
    lastToken = JavaToken.RESERVED_WORD_CONST;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 451: break;
        case 285: 
          {  
    lastToken = JavaToken.RESERVED_WORD_CATCH;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 452: break;
        case 284: 
          {  
    lastToken = JavaToken.RESERVED_WORD_CLASS;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 453: break;
        case 282: 
          {  
    lastToken = JavaToken.RESERVED_WORD_SHORT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 454: break;
        case 278: 
          {  
    lastToken = JavaToken.RESERVED_WORD_SUPER;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 455: break;
        case 269: 
          {  
    lastToken = JavaToken.RESERVED_WORD_THROW;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 456: break;
        case 267: 
          {  
    lastToken = JavaToken.RESERVED_WORD_FINAL;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 457: break;
        case 266: 
          {  
    lastToken = JavaToken.RESERVED_WORD_FLOAT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 458: break;
        case 264: 
          {  
    lastToken = JavaToken.RESERVED_WORD_BREAK;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 459: break;
        case 14: 
        case 163: 
          {  
    /* most of these errors have to be caught down near the end of the file.
     * This way, previous expressions of the same length have precedence.
     * This is really useful for catching anything bad by just allowing it 
     * to slip through the cracks. 
     */ 
    lastToken = JavaToken.ERROR_UNCLOSED_STRING;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 460: break;
        case 2: 
        case 8: 
        case 9: 
        case 10: 
        case 11: 
        case 12: 
        case 19: 
        case 20: 
        case 21: 
        case 41: 
        case 42: 
        case 43: 
        case 44: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 67: 
        case 68: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 77: 
        case 78: 
        case 79: 
        case 93: 
        case 94: 
        case 95: 
        case 96: 
        case 111: 
        case 112: 
        case 113: 
        case 114: 
        case 115: 
        case 116: 
        case 117: 
        case 118: 
        case 119: 
        case 120: 
        case 121: 
        case 123: 
        case 124: 
        case 125: 
        case 126: 
        case 127: 
        case 128: 
        case 129: 
        case 130: 
        case 131: 
        case 139: 
        case 140: 
        case 142: 
        case 143: 
        case 144: 
        case 145: 
        case 146: 
        case 147: 
        case 149: 
        case 150: 
        case 151: 
        case 153: 
        case 154: 
        case 166: 
        case 167: 
        case 168: 
        case 169: 
        case 170: 
        case 180: 
        case 181: 
        case 182: 
        case 183: 
        case 184: 
        case 185: 
        case 186: 
        case 187: 
        case 188: 
        case 189: 
        case 190: 
        case 191: 
        case 193: 
        case 194: 
        case 195: 
        case 196: 
        case 197: 
        case 198: 
        case 199: 
        case 200: 
        case 201: 
        case 202: 
        case 203: 
        case 204: 
        case 209: 
        case 211: 
        case 212: 
        case 213: 
        case 215: 
        case 216: 
        case 218: 
        case 219: 
        case 230: 
        case 231: 
        case 232: 
        case 234: 
        case 235: 
        case 236: 
        case 237: 
        case 238: 
        case 239: 
        case 240: 
        case 241: 
        case 242: 
        case 244: 
        case 245: 
        case 247: 
        case 248: 
        case 249: 
        case 250: 
        case 252: 
        case 253: 
        case 254: 
        case 255: 
        case 256: 
        case 258: 
        case 259: 
        case 262: 
        case 263: 
        case 265: 
        case 268: 
        case 274: 
        case 275: 
        case 276: 
        case 277: 
        case 279: 
        case 280: 
        case 281: 
        case 283: 
        case 286: 
        case 288: 
        case 289: 
        case 290: 
        case 291: 
        case 292: 
        case 293: 
        case 294: 
        case 295: 
        case 296: 
        case 298: 
        case 301: 
        case 302: 
        case 303: 
        case 308: 
        case 309: 
        case 311: 
        case 312: 
        case 314: 
        case 316: 
        case 317: 
        case 318: 
        case 319: 
        case 322: 
        case 323: 
        case 324: 
        case 325: 
        case 329: 
        case 333: 
        case 334: 
        case 335: 
        case 336: 
        case 337: 
        case 338: 
        case 339: 
        case 340: 
        case 343: 
        case 344: 
        case 348: 
        case 350: 
        case 351: 
        case 352: 
        case 353: 
        case 356: 
        case 358: 
        case 359: 
        case 361: 
        case 364: 
          {  
    lastToken = JavaToken.IDENTIFIER;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 461: break;
        case 66: 
          {  
    lastToken = JavaToken.OPERATOR_MOD_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 462: break;
        case 80: 
        case 158: 
        case 159: 
          {  
    lastToken = JavaToken.ERROR_UNCLOSED_CHARACTER;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 463: break;
        case 85: 
          {  
    lastToken = JavaToken.COMMENT_END_OF_LINE;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 464: break;
        case 88: 
          {  
    lastToken = JavaToken.OPERATOR_MULTIPLY_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 465: break;
        case 90: 
          {  
    lastToken = JavaToken.OPERATOR_ADD_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 466: break;
        case 92: 
          {  
    lastToken = JavaToken.OPERATOR_SUBTRACT_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 467: break;
        case 102: 
          {  
    lastToken = JavaToken.OPERATOR_SHIFT_RIGHT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 468: break;
        case 103: 
          {  
    lastToken = JavaToken.OPERATOR_LESS_THAN_OR_EQUAL;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 469: break;
        case 104: 
          {  
    lastToken = JavaToken.OPERATOR_SHIFT_LEFT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 470: break;
        case 106: 
          {  
    lastToken = JavaToken.OPERATOR_BITWISE_AND_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 471: break;
        case 107: 
          {  
    lastToken = JavaToken.OPERATOR_LOGICAL_AND;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 472: break;
        case 109: 
          {  
    lastToken = JavaToken.OPERATOR_LOGICAL_OR;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 473: break;
        case 110: 
          {  
    lastToken = JavaToken.OPERATOR_BITWISE_XOR_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 474: break;
        case 177: 
          {  
    lastToken = JavaToken.OPERATOR_SHIFT_RIGHT_ASSIGN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 475: break;
        case 273: 
          { 
    lastToken = JavaToken.COMMENT_TRADITIONAL;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 476: break;
        case 39: 
          { 
    lastToken = JavaToken.OPERATOR_BITWISE_OR;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 477: break;
        case 33: 
          { 
    lastToken = JavaToken.OPERATOR_LESS_THAN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 478: break;
        case 29: 
          { 
    lastToken = JavaToken.SEPARATOR_SEMICOLON;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 479: break;
        case 28: 
          { 
    lastToken = JavaToken.SEPARATOR_RBRACKET;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 480: break;
        case 27: 
          { 
    lastToken = JavaToken.SEPARATOR_LBRACKET;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 481: break;
        case 313: 
          { 
    lastToken = JavaToken.RESERVED_WORD_STATIC;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 482: break;
        case 227: 
          { 
    lastToken = JavaToken.COMMENT_DOCUMENTATION;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 483: break;
        case 52: 
        case 171: 
          { 
    /* Sun s java has a few bugs here.  Their MAX_FLOAT and MIN_FLOAT do not
     * quite match the spec.  Its not far off, so we will deal.  If they fix
     * then we are fixed.  So all good.
     */ 
    Float f;
    try {
        f = Float.valueOf(yytext());
        if (f.isInfinite() || f.compareTo(new Float(0f)) == 0){
            lastToken = JavaToken.ERROR_FLOAT_SIZE;
        } else {
            lastToken = JavaToken.LITERAL_FLOATING_POINT;
        }
    } catch (NumberFormatException e){
        lastToken = JavaToken.ERROR_FLOAT_SIZE;
    }
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 484: break;
        case 40: 
          { 
    lastToken = JavaToken.OPERATOR_BITWISE_XOR;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 485: break;
        case 38: 
          { 
    lastToken = JavaToken.OPERATOR_BITWISE_AND;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 486: break;
        case 34: 
          { 
    lastToken = JavaToken.OPERATOR_LOGICAL_NOT;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 487: break;
        case 32: 
          { 
    lastToken = JavaToken.OPERATOR_GREATER_THAN;
    String text = yytext();
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 488: break;
        case 3: 
        case 4: 
          { 
    /* At this point, the number we found could still be too large.
     * If it is too large, we need to return an error.
     * Java has methods built in that will decode from a string
     * and throw an exception the number is too large 
     */     
    String text = yytext();
    try {
        /* bigger negatives are allowed than positives.  Thus
         * we have to be careful to make sure a neg sign is preserved
         */
        if (lastToken == JavaToken.OPERATOR_SUBTRACT){
            Integer.decode('-' + text);
        } else {
            Integer.decode(text);
        }
        lastToken = JavaToken.LITERAL_INTEGER_DECIMAL;
    } catch (NumberFormatException e){
        lastToken = JavaToken.ERROR_INTEGER_DECIMIAL_SIZE;
    }
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 489: break;
        case 134: 
          { 
    /* An Octal number cannot be too big.  After removing 
     * initial zeros, It can have 23 digits, the first
     * of which must be 1 or less.  The last will be the L or l
     * at the end.
     */
    lastToken = JavaToken.LITERAL_LONG_OCTAL;
    int i; 
    String text = yytext();
    int length = text.length();
    for (i=1 ; i<length-23; i++){
        //check for initial zeros
        if (text.charAt(i) != '0'){ 
            lastToken = JavaToken.ERROR_LONG_OCTAL_SIZE;
        }
    }
    if (length - i > 23){
        lastToken = JavaToken.ERROR_LONG_OCTAL_SIZE;
    } else if (length - i == 23){
        // if the rest of the number is as big as possible
        // the first digit can only be 3 or less
        if (text.charAt(i) != '0' && text.charAt(i) != '1'){
            lastToken = JavaToken.ERROR_LONG_OCTAL_SIZE;
        }
    }
    // Otherwise, it should be OK  
    JavaToken t = (new JavaToken(lastToken,text,yyline,yychar,yychar+text.length(),nextState));
    return (t);
 }
        case 490: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            return null;
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
