package dji.pilot.flyforbid;

public enum a$b {
    CLEAR_MAP_OUTER_MARKER,
    REFRESH_MAP_OUTER_MARKER,
    DIMISS_FORBID_DLG,
    SHOW_FORBID_DLG,
    REFRESH_MAP_MARKER,
    SHOW_STRONG_WARNING_CHECK_DLG,
    SHOW_TAKEOFF_FORBID_DLG
}
