package dji.sdk.api.simulator;

public class DJISimulatorCommend {
    public double altitude;
    public int gpsCount;
    public boolean isBatterySim;
    public boolean isModeFromThridPart;
    public boolean isUseRealRC;
    public double latitude;
    public double longitude;
    public boolean mAccelerateX;
    public boolean mAccelerateY;
    public boolean mAccelerateZ;
    public boolean mGearState;
    public boolean mGyroX;
    public boolean mGyroY;
    public boolean mGyroZ;
    public boolean mLEDColor;
    public boolean mLatitude;
    public boolean mLongitude;
    public boolean mPitch;
    public boolean mPositionX;
    public boolean mPositionY;
    public boolean mPositionZ;
    public boolean mQuaternion;
    public boolean mRoll;
    public boolean mRpm1;
    public boolean mRpm2;
    public boolean mRpm3;
    public boolean mRpm4;
    public boolean mRpm5;
    public boolean mRpm6;
    public boolean mRpm7;
    public boolean mRpm8;
    public boolean mSimTime;
    public boolean mVelocityY;
    public boolean mVelocityZ;
    public boolean mVeloctiyX;
    public boolean mYaw;
    public int pushHz;
}
