package dji.pilot2.share.mode;

import dji.pilot.R;

public class b {
    public static final b[] e = new b[]{new b(R.string.v2_share_to_weixin_friend, R.drawable.v2_share_weixinhaoyou_selected, R.drawable.v2_btn_wechat_session_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT), new b(R.string.v2_share_to_weixin_moment, R.drawable.v2_share_pengyouuquan_selected, R.drawable.v2_btn_wechat_timeline_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT_MOMENTS), new b(R.string.v2_share_to_qq, R.drawable.v2_share_qq_selected, R.drawable.v2_btn_qq_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_QQ), new b(R.string.v2_share_to_sina_weibo, R.drawable.v2_share_weibo_selected, R.drawable.v2_btn_sina_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WEIBO), new b(R.string.v2_share_to_instagram, R.drawable.v2_share_instagram_selected, R.drawable.v2_share_instagram_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_INSTAGRAM), new b(R.string.v2_share_to_facebook, R.drawable.v2_share_facebook_selected, R.drawable.v2_btn_facebook_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_FACKBOOK), new b(R.string.v2_share_to_whatsapp, R.drawable.v2_share_whatapps_selected, R.drawable.v2_btn_whatsapp_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WHATSAPP), new b(R.string.v2_share_to_copy_to_clip_board, R.drawable.v2_share_safari_selected, R.drawable.v2_btn_copy_url_sharing, dji.pilot2.share.e.a.b.COPY_CHAINED_ADDRESS)};
    public static final b[] f = new b[]{new b(R.string.v2_share_to_whatsapp, R.drawable.v2_share_whatapps_selected, R.drawable.v2_btn_whatsapp_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WHATSAPP), new b(R.string.v2_share_to_facebook, R.drawable.v2_share_facebook_selected, R.drawable.v2_btn_facebook_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_FACKBOOK), new b(R.string.v2_share_to_instagram, R.drawable.v2_share_instagram_selected, R.drawable.v2_share_instagram_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_INSTAGRAM), new b(R.string.v2_share_to_twitter, R.drawable.v2_share_twitter_selected, R.drawable.v2_btn_twitter_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_TWITTER), new b(R.string.v2_share_to_weixin_friend, R.drawable.v2_share_weixinhaoyou_selected, R.drawable.v2_btn_wechat_session_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT), new b(R.string.v2_share_to_weixin_moment, R.drawable.v2_share_pengyouuquan_selected, R.drawable.v2_btn_wechat_timeline_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT_MOMENTS), new b(R.string.v2_share_to_qq, R.drawable.v2_share_qq_selected, R.drawable.v2_btn_qq_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_QQ), new b(R.string.v2_share_to_copy_to_clip_board, R.drawable.v2_share_safari_selected, R.drawable.v2_btn_copy_url_sharing, dji.pilot2.share.e.a.b.COPY_CHAINED_ADDRESS)};
    public static final b[] g = new b[]{new b(R.string.v2_share_to_weixin_friend, R.drawable.v2_share_weixinhaoyou_selected, R.drawable.v2_btn_wechat_session_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT), new b(R.string.v2_share_to_weixin_moment, R.drawable.v2_share_pengyouuquan_selected, R.drawable.v2_btn_wechat_timeline_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT_MOMENTS), new b(R.string.v2_share_to_qq, R.drawable.v2_share_qq_selected, R.drawable.v2_btn_qq_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_QQ), new b(R.string.v2_share_to_sina_weibo, R.drawable.v2_share_weibo_selected, R.drawable.v2_btn_sina_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WEIBO), new b(R.string.v2_share_to_instagram, R.drawable.v2_share_instagram_selected, R.drawable.v2_share_instagram_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_INSTAGRAM), new b(R.string.v2_share_to_facebook, R.drawable.v2_share_facebook_selected, R.drawable.v2_btn_facebook_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_FACKBOOK), new b(R.string.v2_share_to_whatsapp, R.drawable.v2_share_whatapps_selected, R.drawable.v2_btn_whatsapp_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WHATSAPP), new b(R.string.v2_share_to_twitter, R.drawable.v2_share_twitter_selected, R.drawable.v2_btn_twitter_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_TWITTER), new b(R.string.v2_share_to_copy_to_clip_board, R.drawable.v2_share_safari_selected, R.drawable.v2_btn_copy_url_sharing, dji.pilot2.share.e.a.b.COPY_CHAINED_ADDRESS)};
    public static final b[] h = new b[]{new b(R.string.v2_share_to_whatsapp, R.drawable.v2_share_whatapps_selected, R.drawable.v2_btn_whatsapp_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WHATSAPP), new b(R.string.v2_share_to_facebook, R.drawable.v2_share_facebook_selected, R.drawable.v2_btn_facebook_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_FACKBOOK), new b(R.string.v2_share_to_instagram, R.drawable.v2_share_instagram_selected, R.drawable.v2_share_instagram_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_INSTAGRAM), new b(R.string.v2_share_to_twitter, R.drawable.v2_share_twitter_selected, R.drawable.v2_btn_twitter_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_TWITTER), new b(R.string.v2_share_to_weixin_friend, R.drawable.v2_share_weixinhaoyou_selected, R.drawable.v2_btn_wechat_session_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT), new b(R.string.v2_share_to_weixin_moment, R.drawable.v2_share_pengyouuquan_selected, R.drawable.v2_btn_wechat_timeline_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT_MOMENTS), new b(R.string.v2_share_to_qq, R.drawable.v2_share_qq_selected, R.drawable.v2_btn_qq_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_QQ), new b(R.string.v2_share_to_sina_weibo, R.drawable.v2_share_weibo_selected, R.drawable.v2_btn_sina_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WEIBO), new b(R.string.v2_share_to_copy_to_clip_board, R.drawable.v2_share_safari_selected, R.drawable.v2_btn_copy_url_sharing, dji.pilot2.share.e.a.b.COPY_CHAINED_ADDRESS)};
    public static final b[] i = new b[]{new b(R.string.v2_share_to_weixin_moment, R.drawable.v2_share_pengyouuquan_selected, R.drawable.v2_btn_wechat_timeline_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT_MOMENTS), new b(R.string.v2_share_to_weixin_friend, R.drawable.v2_share_weixinhaoyou_selected, R.drawable.v2_btn_wechat_session_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT), new b(R.string.v2_share_to_sina_weibo, R.drawable.v2_share_weibo_selected, R.drawable.v2_btn_sina_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WEIBO), new b(R.string.v2_share_to_qq, R.drawable.v2_share_qq_selected, R.drawable.v2_btn_qq_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_QQ), new b(R.string.v2_share_to_copy_to_clip_board, R.drawable.v2_share_safari_selected, R.drawable.v2_btn_copy_url_sharing, dji.pilot2.share.e.a.b.COPY_CHAINED_ADDRESS), new b(R.string.v2_coupon_giftshare_sms, R.drawable.v2_coupon_share_sms, R.drawable.v2_coupon_share_sms, dji.pilot2.share.e.a.b.PLATFORM_TYPE_SMS), new b(R.string.v2_coupon_giftshare_mail, R.drawable.v2_coupon_share_mail, R.drawable.v2_coupon_share_mail, dji.pilot2.share.e.a.b.PLATFORM_TYPE_MAIL)};
    public static final b[] j = new b[]{new b(R.string.v2_share_to_facebook, R.drawable.v2_share_facebook_selected, R.drawable.v2_btn_facebook_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_FACKBOOK), new b(R.string.v2_share_to_twitter, R.drawable.v2_share_twitter_selected, R.drawable.v2_btn_twitter_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_TWITTER), new b(R.string.v2_share_to_whatsapp, R.drawable.v2_share_whatapps_selected, R.drawable.v2_btn_whatsapp_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WHATSAPP), new b(R.string.v2_share_to_weixin_moment, R.drawable.v2_share_pengyouuquan_selected, R.drawable.v2_btn_wechat_timeline_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT_MOMENTS), new b(R.string.v2_share_to_weixin_friend, R.drawable.v2_share_weixinhaoyou_selected, R.drawable.v2_btn_wechat_session_sharing, dji.pilot2.share.e.a.b.PLATFORM_TYPE_WECHAT), new b(R.string.v2_share_to_copy_to_clip_board, R.drawable.v2_share_safari_selected, R.drawable.v2_btn_copy_url_sharing, dji.pilot2.share.e.a.b.COPY_CHAINED_ADDRESS), new b(R.string.v2_coupon_giftshare_sms, R.drawable.v2_coupon_share_sms, R.drawable.v2_coupon_share_sms, dji.pilot2.share.e.a.b.PLATFORM_TYPE_SMS), new b(R.string.v2_coupon_giftshare_mail, R.drawable.v2_coupon_share_mail, R.drawable.v2_coupon_share_mail, dji.pilot2.share.e.a.b.PLATFORM_TYPE_MAIL)};
    public int a;
    public int b;
    public int c;
    public dji.pilot2.share.e.a.b d;

    public b(int i, int i2, int i3, dji.pilot2.share.e.a.b bVar) {
        this.a = i;
        this.b = i2;
        this.c = i3;
        this.d = bVar;
    }
}
