package dji.pilot2.publics.b;

public interface a$d {
    public static final int a = 3;
    public static final String[] b = new String[]{"file:///android_asset/htmls/connect_kumquat.html", "file:///android_asset/htmls/connect_inspire_1.html", "file:///android_asset/htmls/connect_inspire_1.html", "file:///android_asset/htmls/connect_inspire_1.html", "file:///android_asset/htmls/connect_phantom_4.html", "file:///android_asset/htmls/connect_phantom_3.html", "file:///android_asset/htmls/connect_phantom_3.html", "file:///android_asset/htmls/connect_phantom_3C.html", "file:///android_asset/htmls/connect_matrice_100.html", "file:///android_asset/htmls/connect_matrice_600.html", "file:///android_asset/htmls/connect_matrice_600.html", "file:///android_asset/htmls/connect_osmo.html", "file:///android_asset/htmls/connect_osmo.html", "file:///android_asset/htmls/connect_osmo.html", "file:///android_asset/htmls/connect_osmo.html"};
    public static final String[] c = new String[]{"file:///android_asset/htmls/connect_kumquat_en.html", "file:///android_asset/htmls/connect_inspire_1_en.html", "file:///android_asset/htmls/connect_inspire_1_en.html", "file:///android_asset/htmls/connect_inspire_1_en.html", "file:///android_asset/htmls/connect_phantom_4_en.html", "file:///android_asset/htmls/connect_phantom_3_en.html", "file:///android_asset/htmls/connect_phantom_3_en.html", "file:///android_asset/htmls/connect_phantom_3C_en.html", "file:///android_asset/htmls/connect_matrice_100_en.html", "file:///android_asset/htmls/connect_matrice_600.html", "file:///android_asset/htmls/connect_matrice_600.html", "file:///android_asset/htmls/connect_osmo_en.html", "file:///android_asset/htmls/connect_osmo_en.html", "file:///android_asset/htmls/connect_osmo_en.html", "file:///android_asset/htmls/connect_osmo_en.html"};
    public static final String[] d = new String[]{"http://%1$s.dji.com/%2$sproduct/inspire-1-pro?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/inspire-1?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/phantom-3-professional?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/phantom-3-professional?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/phantom-3-advanced?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/phantom-3-standard?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/matrice-100?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/osmo?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/dji-lightbridge-2?dji_from=dji-pilot-app"};
    public static final String[] e = new String[]{"http://%1$s.dbeta.me/%2$sproduct/inspire-1-pro?dji_from=dji-pilot-app", "http://%1$s.dbeta.me/%2$sproduct/inspire-1?dji_from=dji-pilot-app", "http://%1$s.dbeta.me/%2$sproduct/phantom-3-professional?dji_from=dji-pilot-app", "http://%1$s.dbeta.me/%2$sproduct/phantom-3-professional?dji_from=dji-pilot-app", "http://%1$s.dbeta.me/%2$sproduct/phantom-3-advanced?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/phantom-3-standard?dji_from=dji-pilot-app", "http://%1$s.dbeta.me/%2$sproduct/matrice-100?dji_from=dji-pilot-app", "http://%1$s.dbeta.me/%2$sproduct/osmo?dji_from=dji-pilot-app", "http://%1$s.dji.com/%2$sproduct/dji-lightbridge-2?dji_from=dji-pilot-app"};
}
