package dji.pilot.fpv.camera.more;

public enum a$a {
    PHOTOTYPE_CHANGED,
    PHOTOTYPE_CHANGED_AUTO,
    CAMERAINFO_GETTED,
    MF_DEMARCATE,
    CENTER_POINT_CHANGED,
    CENTER_POINT_COLOR_CHANGED,
    LINEREF_CHANGED,
    LINEREF_COLOR_CHANGED,
    LINEREF_CUSTOMATTR_CHANGED
}
